<div class="row">
    <div class="col-sm-12">
        <div class="panel">
            <div class="panel-heading">
                <h4>Registro de personas</h4>
            </div>
            <div class="panel-body">        
                <div class="tab-content">
                    <!-- <div id="domshortcuttiles" class="tab-pane active"> -->
                    <div class="row">
                        <div class="panel panel-info">

                            <div class="panel-body">
                                <div class="alert alert-info">
                                    <p>Llene correctamente los datos del formulario, los campos con (<span class="text-danger">*</span>) son obligatorios.</p>
                                </div>
                                <div class="row ">
                                    <div class="col-md-12">
                                        <?php echo $this->flashSession->output(); ?>        
                                    </div>
                                </div>

                                    <!-- <div class="row">
                                        <div id="container_image"></div> 
                                    </div> -->
                                    <div class="row">
                                        <div class="col-md-10">
                                                <form action="" method="post" id="wizard" class="form-horizontal">
                                                    <input type="hidden" id="link_foto" name="id" value="">
                                                    <input type="hidden" id="id" name="id" value="">
                                                    <fieldset title="Paso 1">
                                                        <legend>Datos Personales</legend>

                                                        <div class="row">
                                                            <div class="col-md-12">  
                                                                <div class="form-group">
                                                                    <label class="col-md-4 control-label" for="val_p_nombre">Nombre(s)<span class="text-danger">*</span></label>

                                                                    <div class="col-md-8">
                                                                        <div class="input-group col-md-12 ">
                                                                            <input type="text" id="p_nombre" name="p_nombre" class="form-control" title="Campo requerido" placeholder="Primer nombre" required="" />                                                                                
                                                                        </div>  
                                                                    </div>  
                                                                </div>  
                                                                <div class="form-group">
                                                                    <label class="col-md-4 control-label" for="val_p_nombre"><span class="text-danger"></span></label>
                                                                    <div class="col-md-8">
                                                                        <div class="input-group col-md-12">
                                                                            <input type="text" id="s_nombre" name="s_nombre" class="form-control" placeholder="segundo nombre" />

                                                                        </div>  
                                                                    </div>  
                                                                </div>  
                                                            </div>
                                                        </div>
                                                    </fieldset>
                                                    <fieldset title="Paso 2">
                                                        <legend>Datos de contacto</legend>
                                                        <div class="row">
                                                            <div class="col-md-12">
                                                                <div class="form-group ">
                                                                    <label class="col-md-4 control-label" for="val_direccion">Direcci&oacute;n<span class="text-danger">*</span></label>                                
                                                                    <div class="col-md-8">
                                                                        <div class="input-group ">
                                                                            <input type="text" id="s_apellido" name="direccion" class="form-control" placeholder="Calle, # , zona" required="" title="campo requerido" />
                                                                            <span class="input-group-addon"><i class="gi gi-home"></i></span>                                                                      
                                                                        </div>  
                                                                    </div>  
                                                                </div>  

                                                                <div class="form-group ">
                                                                    <label class="col-md-4 control-label" for="val_telefono">Telefono:</label>
                                                                    <div class="col-md-8">
                                                                        <div class="input-group ">
                                                                            <input type="text" id="telefono" name="telefono" class="form-control" placeholder="2-2213344" />
                                                                            <span class="input-group-addon"><i class="gi gi-phone_alt"></i></span>                                  
                                                                        </div>  
                                                                    </div>  
                                                                </div>  

                                                                <div class="form-group ">
                                                                    <label class="col-md-4 control-label" for="val_celular">Celular<span class="text-danger">*</span></label>

                                                                    <div class="col-md-8">
                                                                        <div class="input-group ">
                                                                            <input type="text" id="celular" name="celular" class="form-control" placeholder="777554433" required="" title="campo requerido"/>
                                                                            <span class="input-group-addon"><i class="gi gi-iphone"></i></span>                                  
                                                                        </div>  
                                                                    </div> 
                                                                </div> 
                                                                
                                                            </div> 
                                                                  
                                                        </div>
                                                    </fieldset>
                                                    <fieldset title="Paso 3">
                                                        <legend>Otros datos</legend>
                                                        <div class="row">

                                                            <div class="col-md-6">
                                                                <div class="form-group ">
                                                                    <label class="col-md-4 control-label" for="val_direccion">NIT</label>                                
                                                                    <div class="col-md-8">
                                                                        <div class="input-group ">
                                                                            <input type="text" id="nit" name="nit" class="form-control" placeholder="4021530010" />
                                                                            <span class="input-group-addon"><i class="gi gi-home"></i></span>                                                                      
                                                                        </div>  
                                                                    </div>  
                                                                </div>  

                                                                <div class="form-group">
                                                                    <label class="col-md-4 control-label" for="val_username">Funcionario SIGMA</label>                    

                                                                    <div class="col-md-8">
                                                                        <div class="input-group col-md-12 ">
                                                                            <input type="text" id="sigma" name="sigma" class="form-control " placeholder="" />
                                                                            <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>                                  
                                                                        </div>  
                                                                    </div>  
                                                                </div>  
                                                                <div class="form-group">
                                                                    <label class="col-md-4 control-label" for="val_username">Libreta Militar</label>                    

                                                                    <div class="col-md-8">
                                                                        <div class="input-group col-md-12 ">
                                                                            <input type="text" id="libreta" name="libreta" class="form-control " placeholder="" />
                                                                            <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>                                  
                                                                        </div>  
                                                                    </div>  
                                                                </div>  
                                                                <div class="form-group">
                                                                    <label class="col-md-4 control-label" for="val_reg_profecional">Registro Prof.</label>                    

                                                                    <div class="col-md-8">
                                                                        <div class="input-group col-md-12 ">
                                                                            <input type="text" id="reg_profesional" name="reg_profesional" class="form-control " placeholder="" />
                                                                            <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>                                  
                                                                        </div>  
                                                                    </div>  
                                                                </div>  

                                                            </div> 
                                                        </div> 
                                                    </fieldset>
                                                    <input type="submit" name="submit" class="finish btn-success btn" title="Registrar persona" value="Registrar" />
                                                </form>
                                        </div>
                                    </div>
                                    
                                    
                                    
                                </div>
                            </div>
                        </div>


                        <!-- </div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>



