<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<h4>Listado de Clientes</h4>
				<div class="options">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
						<li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="panel-body">
				<div class="tab-content">
					<div class="row">
						<div class="col-sm-6 col-lg-3">
							<div class="widget">
								<div class="widget-simple">
									<a href="./page_ready_user_profile.php.html">
										<img src="/images/a1.jpg" alt="avatar" class="widget-image img-circle pull-left" />
									</a>
									<h4 class="widget-content">
										<a href="./page_ready_user_profile.php.html" class="themed-color">
											<strong class="text-primary">Nelica Blanco</strong>
										</a>
										<small class="text-success">Cel. 70669687</small>
										<span class="label label-primary">Contacto</span>
									</h4>
								</div>
								<div class="panel panel-primary">
								<div class="panel-heading" align="center"> CONTRATOS </div>
									<div class="panel-body" align="center">
										<div class="col-xs-6">
											<div><b>56</b></div>
											<div>Concluidos</div>
										</div>
										<div class="col-xs-6">
											<div><b>56</b></div>
											<div>Activos</div>
										</div>
									</div>
								</div>
								<div class="widget-extra">
									<div class="row text-center themed-background-dark">
										<div class="col-xs-4">
											<h3 class="widget-content-light">
												<small>25,000.00</small><br>
												<small>TOTAL</small><br />
											</h3>
										</div>
										<div class="col-xs-4">
											<h3 class="widget-content-light">
												<small>25,000.00</small><br>
												<small>DEPOSITOS</small>
											</h3>
										</div>
										<div class="col-xs-4">
											<h3 class="widget-content-light">
												<small>25,000.00</small><br>
												<small>MORA</small><br />
											</h3>
										</div>
									</div>
								</div>
								

							</div>
						</div>
						<div class="col-lg-9">
							hola como askdfjlaskdjf
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>