

<div class="row">
    <div class="col-lg-12">
        <div class="panel">
            <div class="panel-heading">
                <h4>Lista de Cargos</h4>
                <div class="options">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-sitemap"></i></a></li>                        
                    </ul>
                </div>

            </div>

        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="pull-right">
            <button class="btn btn-sm btn-primary-alt" type="button" id="add"><i class="fa fa-plus fa-fw "></i>Adicionar</button>
            <button class="btn btn-sm btn-warning-alt" type="button" id="edit"><i class="fa fa-pencil fa-fw "></i> Editar</button>
            <button class="btn btn-sm btn-danger-alt" type="button" id="delete"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
            <button class="btn btn-sm btn-primary-alt" type="button" id="add_pac"><i class="fa fa-sign-in fa-fw"></i> Asignar PACP</button>
            <button class="btn btn-sm btn-primary-alt" type="button" id="rep_pdf"><i class="fa fa-book fa-fw"></i> Reporte</button>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-10 col-md-10 col-xs-12">
        <div style="width: 100%; height: 350px;  " id="jqxgrid"></div>
    </div>
    <div class="col-lg-2 col-md-2 col-xs-12">
        <div style="width: 100%;" id="jqxlistbox"></div>
    </div>

</div>


<div class="row">
    <div class="">
        <h4>Plan Anual de Contrataciones de Personal</h4>	
    </div>
</div>
<div class="row">            
    <div class="col-lg-12">
        <div class=" pull-right">
            <button class="btn btn-sm btn-danger" type="button" id="delete_pac"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
            <button class="btn btn-sm btn-primary" type="button" id="rep_pdf_pac"><i class="fa fa-book fa-fw"></i> Reporte</button>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div id="jqxgrid2" style="width: 100%; height: 350px;  "></div>
    </div>

</div>

<!-- Modal add / edit Cargos-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo">REGISTRAR EN EL PLAN ANUAL DE CONTRATACIONES DE PERSONAL</h4>
            </div>
            <div class="modal-body">

                <input id="id" name="id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Organigrama</label>
                    <div class="col-md-9">
                        <?php echo $organigrama ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Depende de</label>
                    <div class="col-md-9">
                        <select name="depende_id" id="depende_id" class="form-control">
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Nivel Salarial</label>
                    <div class="col-md-9">
                        <?php echo $nivelsalarial; ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Salario Mensual</label>
                    <div class="col-md-9">
                        <span id="sueldotxt"></span> Bs.
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Item</label>
                    <div class="col-md-9">
                        <input id="codigo" name="codigo" type="text" class="form-control"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Cargo</label>
                    <div class="col-md-9">
                        <input id="cargo" name="cargo" type="text" class="form-control"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Fuente Financiamiento</label>
                    <div class="col-md-9">
                        <?php echo $finpartida; ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Formación y Experiencia Laboral</label>
                    <div class="col-md-9">
                        <textarea name="formacion_requerida" id="formacion_requerida" class="form-control"><?php echo $v->formacion_requerida; ?></textarea>
                    </div>
                </div>



            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="save">Guardar</button>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- end  modal -->


<!-- Modal PACP-->
<div class="modal fade" id="myModal_pac" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_pac" data-toggle="validator"/>
            <input id="cargo_id_pac" name="cargo_id_pac" type="hidden" />
            <input id="estado_cargo" name="estado_cargo" type="hidden" />
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo_pac">REGISTRAR EN EL PLAN ANUAL DE CONTRATACIONES DE PERSONAL</h4>
            </div>
            <div class="modal-body">

                <input id="id_pac" name="id_pac" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Organigrama</label>
                    <div class="col-md-9">
                        <div id="organigrama_pac"></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Item</label>
                    <div class="col-md-9">
                        <div id="item_pac"></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Cargo</label>
                    <div class="col-md-9">
                        <div id="cargo_pac"></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Salario Mensual</label>
                    <div class="col-md-9">
                        <div id="sueldo_pac"></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Gestión</label>
                    <div class="col-md-9">
                        <input id="gestion_pac" name="gestion_pac" type="text" value="<?php echo date("Y"); ?>" class="form-control"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Fecha Inicio</label>
                    <div class="col-md-9">
                        <!-- <div id="fecha_ini_pac"></div> -->
                        <input type="text" id="fecha_ini_pac" name="fecha_ini_pac" value="<?php echo date("d-m-Y") ?>" class="form-control input-datepicker-close" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Fecha Finalización</label>
                    <div class="col-md-9">
                        <!-- <div id="fecha_fin_pac"></div> -->
                        <input type="text" id="fecha_fin_pac" name="fecha_fin_pac" value="<?php echo date("d-m-Y") ?>" class="form-control input-datepicker-close" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
                    </div>
                </div>



            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="guardar_pac">Guardar</button>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- end  modal -->

<!-- Modal Reporte-->
<div class="modal fade" id="myModal_rep" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_rep" data-toggle="validator" action="/cargos/exportarExcel/" method="POST" target="_blank" />
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo">FORMULARIO DE REPORTES</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="col-md-3 control-label" >Organigrama</label>
                    <div class="col-md-9">
                        <?php echo $organigrama ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Estado</label>
                    <div class="col-md-9">
                        <select name="estado_rep" id="estado_rep" class="form-control select-chosen">
                            <option value="0">(Seleccionar)</option>
                            <option value="1">ADJUDICADO</option>
                            <option value="2">ACEFALO</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Tipo</label>
                    <div class="col-md-9">
                        <?php echo $condicion ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <!-- <button type="submit" class="btn btn-primary" id="exportar_excel">Exportar Excel</button> -->
                <button type="submit" class="btn btn-primary" id="exportar_pdf">Exportar PDF</button>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- end  modal -->


<!-- Modal Reporte-->
<div class="modal fade" id="myModal_rep_pac" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_rep_pac" data-toggle="validator" action="" method="POST" target="_blank" />
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo">FORMULARIO DE REPORTES</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="col-md-3 control-label" >Organigrama</label>
                    <div class="col-md-9">
                        <?php echo $organigrama_rep_pac ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Fecha Inicio Desde</label>
                    <div class="col-md-9">
                        <input type="text" id="fecha_ini_rep_pac" name="fecha_ini_rep_pac" value="<?php echo date("d-m-Y") ?>" class="form-control input-datepicker-close" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Hasta</label>
                    <div class="col-md-9">
                        <input type="text" id="fecha_fin_rep_pac" name="fecha_fin_rep_pac" value="<?php echo date("d-m-Y") ?>" class="form-control input-datepicker-close" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <!-- <button type="submit" class="btn btn-primary" id="exportar_excel">Exportar Excel</button> -->
                <button type="submit" class="btn btn-primary" id="exportar_pac_pdf">Exportar PDF</button>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- end  modal -->

<style type="text/css">
    .datepicker{
        z-index:1151;
    }
</style>