<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<h4>Seguimiento Hoja de Ruta</h4>
				<div class="options">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
						<li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="panel-body">
				<div class="tab-content">
					<div class="row">
						
						<!-- <div class="card card-underline">
							<div class=" card-head">
								<header>
									<i class="fa fa-tags"></i>
									Hoja de Ruta : MT/2014-02446
								</header>
							</div>
							<div class=" card-body">
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Referencia: </span>
									</div>
									<div class="col-lg-10 col-md-10">
										<span class="text-medium text-primary-dark">INFORME DE ACTIVIDADES</span>
									</div>
								</div>
							</div>
						</div> -->

						<div class="col-md-12">
							<div class="block">
								<div class="block-title">
									<i class="fa fa-tags"></i>
									<h2><strong>Hoja de Ruta :</strong>MT/2014-02446</h2>
								</div>
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Referencia: </span>
									</div>
									<div class="col-lg-10 col-md-10">
										<span class="text-medium text-primary-dark">INFORME DE ACTIVIDADES</span>
									</div>
								</div>
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Documento Original: </span>
									</div>
									<div class="col-lg-5 col-md-5">
										<span class="text-medium">
											<a href="/document/detalle/103717">INF/EETC MT/GPGE/DTI Nº 0058/2014</a>
										</span>
									</div>
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Proceso: </span>
									</div>
									<div class="col-lg-3 col-md-3"> Informe </div>
								</div>
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Destinatario: </span>
									</div>
									<div class="col-lg-5 col-md-5">
										<span class="text-medium">Ivan Marcelo Chacolla M. / RESPONSABLE DE DESARROLLO Y BASE DE DATOS</span>
									</div>
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Tipo Documento: </span>
									</div>
									<div class="col-lg-3 col-md-3">
										<span>Informe</span>
									</div>
								</div>
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Remitente: </span>
									</div>
									<div class="col-lg-5 col-md-5">
										<span class="text-medium">Freddy Velasco / PROFESIONAL EN DESARROLLO Y BASE DE DATOS</span>
									</div>
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Fecha: </span>
									</div>
									<div class="col-lg-3 col-md-3">
										<span class=" opacity-50"> Martes, 11 de Noviembre de 2014 18:11:21 </span>
									</div>
								</div>
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Archivos adjuntos: </span>
									</div>
									<div class="col-lg-10 col-md-10">
										<span class="text-medium"> </span>
									</div>
								</div>
							</div>	
						</div>
						

					</div>
				</div>
			</div>
		</div>
	</div>
</div>