<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<h4>Seguimiento Hoja de Ruta</h4>
				<div class="options">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
						<li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="panel-body">
				<div class="tab-content">
					<div class="row">
						<div class="col-md-12">
							<div class="block">
								<div class="block-title">
									<i class="fa fa-tags"></i>
									<h2><strong>Hoja de Ruta :</strong>MT/2014-02446</h2>
								</div>
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Referencia: </span>
									</div>
									<div class="col-lg-10 col-md-10">
										<span class="text-medium text-primary-dark">INFORME DE ACTIVIDADES</span>
									</div>
								</div>
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Documento Original: </span>
									</div>
									<div class="col-lg-5 col-md-5">
										<span class="text-medium">
											<a href="/document/detalle/103717">INF/EETC MT/GPGE/DTI Nº 0058/2014</a>
										</span>
									</div>
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Proceso: </span>
									</div>
									<div class="col-lg-3 col-md-3"> Informe </div>
								</div>
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Destinatario: </span>
									</div>
									<div class="col-lg-5 col-md-5">
										<span class="text-medium">Ivan Marcelo Chacolla M. / RESPONSABLE DE DESARROLLO Y BASE DE DATOS</span>
									</div>
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Tipo Documento: </span>
									</div>
									<div class="col-lg-3 col-md-3">
										<span>Informe</span>
									</div>
								</div>
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Remitente: </span>
									</div>
									<div class="col-lg-5 col-md-5">
										<span class="text-medium">Freddy Velasco / PROFESIONAL EN DESARROLLO Y BASE DE DATOS</span>
									</div>
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Fecha: </span>
									</div>
									<div class="col-lg-3 col-md-3">
										<span class=" opacity-50"> Martes, 11 de Noviembre de 2014 18:11:21 </span>
									</div>
								</div>
								<div class="row">
									<div class="col-lg-2 col-md-2">
										<span class=" opacity-50">Archivos adjuntos: </span>
									</div>
									<div class="col-lg-10 col-md-10">
										<span class="text-medium"> </span>
									</div>
								</div>
							</div>	
						</div>
					</div>

					<div class="row">
						<div class="col-sm-12">
							<div class="block full">
								<div class="block-title">
									<div class="block-options pull-right">
										<a href="javascript:void(0)" class="btn btn-alt btn-sm btn-default" data-toggle="tooltip" title="Settings"><i class="fa fa-cog"></i></a>
									</div>
									<h2><strong>Timeline</strong> Style</h2>
								</div>
								<div class="timeline block-content-full">
									<ul class="timeline-list timeline-hover">
										<li>
											<div class="timeline-icon"><i class="fa fa-leaf"></i></div>
											<div class="timeline-content">
											<div class="row push">
												<div class="col-lg-5 col-md-5">
													<span class="text-warning text-xl stick-top-right">
														<i class="fa fa-paw"></i>
													</span>
													<span class="text-medium">
														<p>
															<img class="img-circle img-responsive pull-left width-1 " width="110" alt="" src="/static/fotos/ventanilla.jpg">
															<span class="text-medium">
																<a href="/route/oficina/77">UNIDAD ADMINISTRATIVA</a>
																<br>
																<a class="text-primary-dark" href="/users/profile/">Ventanilla Unica</a>
															</span>
															<br>
															<span class="opacity-75"> Encargado de Ventanilla Unica </span>
														</p>
														<span class="opacity-50 pull-right text-light">
															<i class="fa fa-arrow-up"></i>
															Lunes, 10/Jun/2013 - 18:20:43
														</span>
													</span>
												</div>
												<div class="col-lg-5 col-md-5">
													<span class="text-warning text-xl stick-top-right">
														<i id="" class="fa fa-paw"></i>
													</span>
													<span class="text-medium">
														<p>
															<img class="img-circle img-responsive pull-left width-1 " width="110" alt="" src="/static/fotos/hombre.jpg">
															<span class="text-medium">
																<a href="/route/oficina/110">UNIDAD DE TRANSPORTE POR CABLE</a>
																<br>
																<a class="text-primary-dark" href="/users/profile/">Cesar Dockweiler Suárez</a>
															</span>
															<br>
															<span class="opacity-75"> Coordinador General de la UTC </span>
														</p>
														<span class="opacity-50 pull-right text-light">Enviado: Lunes, 10/Jun/2013 - 19:16:02 </span>
													</span>
												</div>
												<div class="col-lg-2 col-md-2">
													<span class=" badge style-info text-medium"> Recibido/Derivado </span>
													<span class=" text-xs">
														<br>
														Adjunto:
														<br>
													</span>
												</div>
											</div>
												

											</div>
										</li>
										<li>
											<div class="timeline-icon"><i class="fa fa-leaf"></i></div>
											<div class="timeline-content">
											<div class="row push">
												<div class="col-lg-5 col-md-5">
													<span class="text-warning text-xl stick-top-right">
														<i class="fa fa-paw"></i>
													</span>
													<span class="text-medium">
														<p>
															<img class="img-circle img-responsive pull-left width-1 " width="110" alt="" src="/static/fotos/ventanilla.jpg">
															<span class="text-medium">
																<a href="/route/oficina/77">UNIDAD ADMINISTRATIVA</a>
																<br>
																<a class="text-primary-dark" href="/users/profile/">Ventanilla Unica</a>
															</span>
															<br>
															<span class="opacity-75"> Encargado de Ventanilla Unica </span>
														</p>
														<span class="opacity-50 pull-right text-light">
															<i class="fa fa-arrow-up"></i>
															Lunes, 10/Jun/2013 - 18:20:43
														</span>
													</span>
												</div>
												<div class="col-lg-5 col-md-5">
													<span class="text-warning text-xl stick-top-right">
														<i id="" class="fa fa-paw"></i>
													</span>
													<span class="text-medium">
														<p>
															<img class="img-circle img-responsive pull-left width-1 " width="110" alt="" src="/static/fotos/hombre.jpg">
															<span class="text-medium">
																<a href="/route/oficina/110">UNIDAD DE TRANSPORTE POR CABLE</a>
																<br>
																<a class="text-primary-dark" href="/users/profile/">Cesar Dockweiler Suárez</a>
															</span>
															<br>
															<span class="opacity-75"> Coordinador General de la UTC </span>
														</p>
														<span class="opacity-50 pull-right text-light">Enviado: Lunes, 10/Jun/2013 - 19:16:02 </span>
													</span>
												</div>
												<div class="col-lg-2 col-md-2">
													<span class=" badge style-info text-medium"> Recibido/Derivado </span>
													<span class=" text-xs">
														<br>
														Adjunto:
														<br>
													</span>
												</div>
											</div>
												

											</div>
										</li>
										<li>
											<div class="timeline-icon"><i class="fa fa-leaf"></i></div>
											<div class="timeline-content">
											<div class="row push">
												<div class="col-lg-5 col-md-5">
													<span class="text-warning text-xl stick-top-right">
														<i class="fa fa-paw"></i>
													</span>
													<span class="text-medium">
														<p>
															<img class="img-circle img-responsive pull-left width-1 " width="110" alt="" src="/static/fotos/ventanilla.jpg">
															<span class="text-medium">
																<a href="/route/oficina/77">UNIDAD ADMINISTRATIVA</a>
																<br>
																<a class="text-primary-dark" href="/users/profile/">Ventanilla Unica</a>
															</span>
															<br>
															<span class="opacity-75"> Encargado de Ventanilla Unica </span>
														</p>
														<span class="opacity-50 pull-right text-light">
															<i class="fa fa-arrow-up"></i>
															Lunes, 10/Jun/2013 - 18:20:43
														</span>
													</span>
												</div>
												<div class="col-lg-5 col-md-5">
													<span class="text-warning text-xl stick-top-right">
														<i id="" class="fa fa-paw"></i>
													</span>
													<span class="text-medium">
														<p>
															<img class="img-circle img-responsive pull-left width-1 " width="110" alt="" src="/static/fotos/hombre.jpg">
															<span class="text-medium">
																<a href="/route/oficina/110">UNIDAD DE TRANSPORTE POR CABLE</a>
																<br>
																<a class="text-primary-dark" href="/users/profile/">Cesar Dockweiler Suárez</a>
															</span>
															<br>
															<span class="opacity-75"> Coordinador General de la UTC </span>
														</p>
														<span class="opacity-50 pull-right text-light">Enviado: Lunes, 10/Jun/2013 - 19:16:02 </span>
													</span>
												</div>
												<div class="col-lg-2 col-md-2">
													<span class=" badge style-info text-medium"> Recibido/Derivado </span>
													<span class=" text-xs">
														<br>
														Adjunto:
														<br>
													</span>
												</div>
											</div>
												

											</div>
										</li>
										<li class="active">
											<div class="timeline-icon"><i class="fa fa-file-text"></i></div>
											<div class="timeline-content">

											</div>
										</li>
										<li>
											<div class="timeline-icon"><i class="fa fa-cutlery"></i></div>
											<div class="timeline-content">

											</div>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>