<!-- <div class="row">
  
  <div id="gauge1" style="float: left;"></div>
 <div id="gaugeValue1" style="position: absolute; top: 235px; left: 132px; font-family: Sans-Serif; text-align: center; font-size: 17px; width: 70px;"></div>
 <div id="gaugeContainer1"></div>
  
</div> -->

    <style>
        html, body {
            padding: 0;
            margin: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
        }
    </style>


 <div id="gaugeContainer"></div>
 