
<div class="row">
    <div class="col-lg-12">
        <h4>Resoluciones</h4>		
    </div>
</div>

<div class="row">
    <div class="col-lg-12">

        <div class="form-group form-actions pull-right">
            <div class="col-xs-12">
                <button class="btn btn-sm btn-primary" type="button" id="add"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                <button class="btn btn-sm btn-warning" type="button" id="edit"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                <button class="btn btn-sm btn-danger" type="button" id="delete"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
            </div>
        </div>
    </div>
</div>
<div class="row"> 
    <div class=" col-lg-12">
        <div id="jqxgrid" style=" width: 100%; height: 450px;"></div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo">Editar</h4>
            </div>
            <div class="modal-body">
                <input id="id" name="id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label">Tipo Resolución</label>
                    <div class="col-md-9">
                        <input id="tipo_resolucion" name="tipo_resolucion" type="text" class="form-control "/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Numero Resolución</label>
                    <div class="col-md-9">
                        <input id="numero_res" name="numero_res" type="text" class="form-control"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Fecha Emisión</label>
                    <div class="col-md-9">
                        <input type="text" id="fecha_emi" name="fecha_emi"  class="form-control  hasDatepicker " value="" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Fecha Aprobación</label>
                    <div class="col-md-9">
                        <input type="text" id="fecha_apr" name="fecha_apr" class="form-control hasDatepicker " value="" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- end  modal -->

<style type="text/css">
    .datepicker{
        z-index:1151;
    }
</style>