<!-- <div class="row">
	<form method="post" action="" class="form-horizontal" id="testForm" enctype="multipart/form-data">
		<div class="form-group">
			<label class="col-lg-4 control-label">Adicinar Imagen</label>
			<div class="col-lg-8">
				<input type="file" name="archivo" id="archivo" class="file" >
			</div>
		</div>
		<div class="row">
			<div class="form-group">
				<div class="col-lg-12" align="center">
					<button type="submit" class="btn btn-primary" id="guardar">Guardar</button>
					<a href="../" class="btn btn-primary">Cancelar</a>
				</div>
			</div>
		</div>
	</form>
</div> -->

<!-- <div class="row">
	<div class="page-header">
		<h1>Bootstrap File Input Example</h1>
	</div>
	<form enctype="multipart/form-data">
		<input id="file-0a" class="file" type="file" multiple data-min-file-count="1">
		<br>
		<button type="submit" class="btn btn-primary">Submit</button>
		<button type="reset" class="btn btn-default">Reset</button>
	</form>
</div> -->
<div class="container kv-main">
<div class="row">
 <form method="post" action="" class="form-horizontal" id="testForm" enctype="multipart/form-data">

 <!-- <div class="form-group">
			<label class="col-lg-2 control-label">Adicinar Imagen</label>
			<div class="col-lg-4">
				<input id="archivo" type="file" name="archivo" multiple class="file" data-overwrite-initial="false" data-min-file-count="1">
			</div>
		</div> -->

		<div class="form-group">
                    <label>Preview File Icon</label>
                    <input id="file-3" type="file" >
                </div>
                
</form>
</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="widget">
				<div class="widget-advanced widget-advanced-alt">
					<div class="widget-header text-left">
						<h3 class="widget-content widget-content-image widget-content-light clearfix">
							<a href="javascript:void(0)" class="widget-icon pull-right">
								<i class="fa fa-picture-o"></i>
							</a>
							<a href="javascript:void(0)" class="themed-color-default">Todos <strong>Productos</strong></a><br />
							<small>8 Photos</small>
						</h3>
					</div>
					<div class="widget-main">
						<div class="gallery gallery-widget" data-toggle="lightbox-gallery">
							<div class="row">
								<div class="col-xs-6 col-sm-3">
									<a href="/file/productos/photo21.jpg" class="gallery-link" title="Image Info">
										<img src="/file/productos/photo21.jpg" alt="image" />
									</a>
								</div>
								<div class="col-xs-6 col-sm-3">
									<a href="/file/productos/photo22.jpg" class="gallery-link" title="Image Info">
										<img src="/file/productos/photo22.jpg" alt="image" />
									</a>
								</div>
								<div class="col-xs-6 col-sm-3">
									<a href="/file/productos/photo18.jpg" class="gallery-link" title="Image Info">
										<img src="/file/productos/photo18.jpg" alt="image" />
									</a>
								</div>
								<div class="col-xs-6 col-sm-3">
									<a href="/file/productos/photo14.jpg" class="gallery-link" title="Image Info">
										<img src="/file/productos/photo14.jpg" alt="image" />
									</a>
								</div>
								<div class="col-xs-6 col-sm-3">
									<a href="/file/productos/photo5.jpg" class="gallery-link" title="Image Info">
										<img src="/file/productos/photo5.jpg" alt="image" />
									</a>
								</div>
								<div class="col-xs-6 col-sm-3">
									<a href="/file/productos/photo24.jpg" class="gallery-link" title="Image Info">
										<img src="/file/productos/photo24.jpg" alt="image" />
									</a>
								</div>
								<div class="col-xs-6 col-sm-3">
									<a href="/file/productos/photo16.jpg" class="gallery-link" title="Image Info">
										<img src="/file/productos/photo16.jpg" alt="image" />
									</a>
								</div>
								<div class="col-xs-6 col-sm-3">
									<a href="/file/productos/photo20.jpg" class="gallery-link" title="Image Info">
										<img src="/file/productos/photo20.jpg" alt="image" />
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
	</div>
</div>

