<div class="row">
	<form method="post" action="" class="form-horizontal" id="testForm" enctype="multipart/form-data">
		<div class="form-group">
			<label class="col-lg-4 control-label">Adicinar Imagen</label>
			<div class="col-lg-8">
				<input type="file" name="archivo" id="archivo" class="file" >
			</div>
		</div>
		<div class="row">
			<div class="form-group">
				<div class="col-lg-12" align="center">
					<button type="submit" class="btn btn-primary" id="guardar">Guardar</button>
					<a href="../" class="btn btn-primary">Cancelar</a>
				</div>
			</div>
		</div>
	</form>
</div>