<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<h4>Listado de Productos</h4>
				<div class="options">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
                        <li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
                    </ul>
                </div>
			</div>
			<div class="panel-body">
				<div class="tab-content">
					<div class="row">
						<div class="col-md-12">
							<?php echo $this->flashSession->output(); ?>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="pull-right">
                                <button class="btn btn-sm btn-primary" type="button" id="add"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                				<button class="btn btn-sm btn-warning" type="button" id="edit"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                				<button class="btn btn-sm btn-danger" type="button" id="delete"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div id="jqxgrid" style="height: 550px; width: 100%;" ></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm" data-toggle="validator"/>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="titulo">Editar</h4>
			</div>
			<div class="modal-body">
				<input id="id" name="id" type="hidden" />
				<div class="form-group">
					<label class="col-md-3 control-label">Linea:</label>
					<div class="col-md-9">
						<?php echo $linea ?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Estación:</label>
					<div class="col-md-9">
						
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Grupo:</label>
					<div class="col-md-9">
						<?php echo $grupo ?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Producto:</label>
					<div class="col-md-9">
						<input type="text" name="producto" id="producto" required>
					</div>
				</div>
				<div class="form-group" id="activo_id">
					<label class="col-md-3 control-label">Codigo</label>
					<div class="col-md-9">
						<input type="text" name="codigo" id="codigo" >
					</div>
				</div>
				<div class="form-group" id="activo_id">
					<label class="col-md-3 control-label">Descripción</label>
					<div class="col-md-9">
						<textarea name="descripcion" id="descripcion"></textarea>
					</div>
				</div>
				<div class="form-group" id="activo_id">
					<label class="col-md-3 control-label">Cantidad</label>
					<div class="col-md-9">
						<input type="number" name="cantidad" id="cantidad" value="1" >
					</div>
				</div>
				<div class="form-group" id="activo_id">
					<label class="col-md-3 control-label">Tiempo</label>
					<div class="col-md-9">
						<?php echo $tiempo ?>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
			</div>
		</form>
	</div>
</div>
</div>
<!-- end  modal -->