<?php
// if (isset($_POST['username'])) {
//     $user = $_POST['username'];
// } else {
//     $user = '';
// }
?>
<!-- BEGIN ERROR BOX -->
<?php  echo $this->flashSession->output(); ?> 
<div class="alert alert-danger hide">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Error!</h4>
    
</div>



                    <div class="row">
                        <div class="col-md-12">
                            <form class="form-horizontal form-bordered" id="testForm" data-toggle="validator" action="" method="post" />
                            <input type="hidden" name="id" id="id">
                            <div class="form-group">
                                <div class="col-md-12" >
                                    <input id="password_nuevo" name="password_nuevo" class="form-control" type="password" placeholder="Nueva Contraseña" required value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12" >
                                    <input id="password_repetir" name="password_repetir" class="form-control" type="password" placeholder="Repetir Nueva Contraseña" required value="">
                                </div>
                            </div>
                            <input type="hidden" value="<?php echo $url ?>" name="url"/>
                            <div class="modal-footer">
                                <div class="text-center">
                                <button type="submit" class="btn btn-primary" id="Save">Guardar</button>    
                                </div>
                                
                            </div>
                        </form>
                        <div class="login-links">
                        <a href="/login"><strong>Ir a Pagina Principal</strong></a>
                    </div>
                </div>
            </div>



