<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<h4> Listado de Parametros Check List</h4>
				<div class="options">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
						<li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
					</ul>
				</div>
			</div>

			<div class="panel-body">
				<div class="tab-content">
					<div class="row">
						<div class="col-md-12">
							<?php echo $this->flashSession->output(); ?>
							<div id="divMsjeExito" class="msjs-alert" hidden="hidden">
								<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
								<h5>
									<i class="fa fa-check-circle"></i>
									<a class="alert-link" href="javascript:void(0)" id="aMsjeExito"></a>
								</h5>
								
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="pull-right">
								<button class="btn btn-sm btn-primary" type="button" id="add"><i class="fa fa-subway"></i>Adicionar</button>
								<button class="btn btn-sm btn-warning" type="button" id="edit"><i class="fa fa-pencil fa-fw"></i> Editar</button>
								<button class="btn btn-sm btn-danger" type="button" id="delete"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
							</div>
						</div>
					</div>
					
					<div class="row">
						<div class="col-md-12">
							<div id="jqxgrid" style="height: 550px; width: 100%;" ></div>
							<input value="Expand All Groups" type="button" id='expandall' />
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<!-- Modal Adicinar archivo -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		
			<form method="post" action="" class="form-horizontal" id="testForm" enctype="multipart/form-data">
			<input type="hidden" name="id" id="id">
			<input type="text" name="contrato_id" id="contrato_id" value="<?php echo $contrato_id ?>">
			<input type="text" name="cliente_id" id="cliente_id" value="<?php echo $cliente_id ?>">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="titulo">Documento Digital</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<div class="col-md-12">
						<input id="file-1" name="file-1" type="file" data-overwrite-initial="false" data-min-file-count="1">
					</div>
				</div>
			</div>
			<!-- <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
			</div> -->
		</form>
	</div>
</div>
</div>
<!-- end  modal -->
