<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<h4>Contrato Nro</h4>
				<div class="options">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
						<li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="panel-body">
				<div class="tab-content">
					<!-- <div class="row">
						<div class="col-md-12">
							<?php //echo $this->flashSession->output(); ?>
							<div id="divMsjeExito" class="msjs-alert" hidden="hidden">
								<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
								<h5>
									<i class="fa fa-check-circle"></i>
									<a class="alert-link" href="javascript:void(0)" id="aMsjeExito"></a>
								</h5>
								
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="pull-right">
								<button class="btn btn-sm btn-primary" type="button" id="add"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
								<button class="btn btn-sm btn-warning" type="button" id="edit"><i class="fa fa-pencil fa-fw"></i> Editar</button>
								<button class="btn btn-sm btn-danger" type="button" id="delete"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
							</div>
						</div>
					</div> -->
					<div class="row">
						<div class="col-md-12">
							<div id="jqxgrid_p" style="height: 550px; width: 100%;" ></div>
						</div>
					</div>
				</div>
				<br>
			
			</div>
		</div>
	</div>
</div>

