<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<h4>Lista de Contratos</h4>
				<div class="options">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
                        <li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
                    </ul>
                </div>
			</div>
			<div class="panel-body">
				<div class="tab-content">
					<div class="row">
						<div class="col-md-12">
							<div id="jqxgrid" style="height: 550px; width: 100%;" ></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

